name: Run JavaScript File

on:
  workflow_dispatch:

jobs:
  run-js-file:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    # - name: Install dependencies
    #   run: npm install
    #   if: exists('package.json') # Only runs if there's a package.json

    - name: Run JavaScript file
      run: node index.js 
